# Generated by Django 4.2.2 on 2023-10-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_category',
            name='Category_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
