# Generated by Django 4.2.6 on 2025-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='enquiry',
            field=models.CharField(default='Just enquiry', max_length=100),
            preserve_default=False,
        ),
    ]
