# Generated by Django 4.2.6 on 2025-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0004_contact_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='enquiry',
            field=models.CharField(default='General Enquiry', max_length=100),
        ),
    ]
