# Generated by Django 4.2.6 on 2025-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP', '0005_alter_contact_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='')),
                ('carousel_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_img',
            field=models.ImageField(blank=True, default='motor.jpg', null=True, upload_to='brands/'),
        ),
    ]
